Repository My-Little-Forum/mylittleforum, pull requests merged in 2018-03, with the labels that each got.

#357 Change project page link
  themes/default/main.tpl
Labels: cleanup

#360 Parameter for folding
  js/main.js
  js/main.min.js
Labels: bug

#362 Add email note
  lang/english.lang
  lang/german.lang
Labels: feature

#365 cursor: pointer; for HTML-element label
  themes/default/style.css
Labels: enhancement

#366 Bugfix, use correct setting name instead name of abandoned setting
  includes/functions.inc.php
Labels: bug
