Repository My-Little-Forum/mylittleforum, pull requests merged in 2018-12, with the labels that each got.

#410 Remove deprecated function each()
  includes/admin.inc.php
  includes/functions.inc.php
  includes/posting.inc.php
Labels: cleanup

#411 Default prompt
  js/admin.js
  js/main.js
  js/posting.js
  js/posting.min.js
Labels: cleanup, feature

#412 Remove password field (admin area)
  includes/admin.inc.php
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/subtemplates/admin.inc.tpl
Labels: cleanup

#414 Fix: subscritions bug that was solved only for legacy branch before
  includes/admin.inc.php
  includes/functions.inc.php
  includes/posting.inc.php
Labels: bug

#416 Update FR translation
  lang/french.lang
Labels: enhancement

#413 Timespan for form completion
  includes/contact.inc.php
  includes/functions.inc.php
  includes/posting.inc.php
  includes/register.inc.php
  install/install.sql
  update/update.sql
  update/update_2.4.8-2.5.php
Labels: cleanup, feature

#423 max. receipt time
  includes/contact.inc.php
  includes/posting.inc.php
  includes/register.inc.php
Labels: bug

#429 LC_NUMERIC
  index.php
Labels: bug

#427 Bayes-based spam filter
  includes/admin.inc.php
  includes/auto_login.inc.php
  includes/entry.inc.php
  includes/functions.inc.php
  includes/index.inc.php
  includes/login.inc.php
  includes/main.inc.php
  includes/posting.inc.php
  includes/rss.inc.php
  includes/search.inc.php
  includes/thread.inc.php
  install/index.php
  install/install.sql
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  modules/b8/b8.php
  modules/b8/degenerator/degenerator_default.php
  modules/b8/lexer/lexer_default.php
  modules/b8/storage/storage_base.php
  modules/b8/storage/storage_mysqli.php
  themes/default/subtemplates/admin.inc.tpl
  themes/default/subtemplates/entry.inc.tpl
  themes/default/subtemplates/posting_delete.inc.tpl
  themes/default/subtemplates/posting_delete_marked.inc.tpl
  themes/default/subtemplates/posting_delete_spam.inc.tpl
  themes/default/subtemplates/posting_flag_ham.inc.tpl
  themes/default/subtemplates/posting_manage_postings.inc.tpl
  themes/default/subtemplates/posting_move.inc.tpl
  themes/default/subtemplates/posting_report_spam.inc.tpl
  update/update_2.4.8-2.5.php
Labels: feature, help wanted, work in progress

#431 msg-tag
  js/posting.js
  js/posting.min.js
Labels: bug, enhancement

#432 remove msg
  js/posting.js
  js/posting.min.js
Labels: cleanup

#433 Comment
  index.php
Labels: cleanup

#434 Remove account
  includes/user.inc.php
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/subtemplates/user_edit.inc.tpl
  themes/default/subtemplates/user_remove_account.inc.tpl
Labels: enhancement, feature

#435 Change user password
  includes/user.inc.php
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/subtemplates/user_edit_pw.inc.tpl
Labels: cleanup
