Repository My-Little-Forum/mylittleforum, pull requests merged in 2018-11, with the labels that each got.

#400 Update norwegian.lang
  lang/norwegian.lang
Labels: enhancement, question, work in progress

#399 add unsubscribing function for messages about replies
  config/db_settings.php
  includes/functions.inc.php
  includes/posting.inc.php
  install/index.php
  install/install.sql
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/subtemplates/posting_unsubscribe.inc.tpl
Labels: feature

#405 Change: removed the workaround for turkish language
  lang/turkish.lang
Labels: cleanup
