Repository My-Little-Forum/mylittleforum, pull requests merged in 2018-04, with the labels that each got.

#364 Uploads management area
  includes/admin.inc.php
  install/install.sql
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/images/image.png
  themes/default/style.css
  themes/default/subtemplates/admin.inc.tpl
  update/update.sql
  update/update_2.4.8-2.5.php
Labels: feature, next major version

#368 Add width and height attributes to img tag of uploaded images
  includes/functions.inc.php
Labels: enhancement

#371 Two errors in russian language file
  lang/russian.lang
Labels: bug

#367 Fix(es) for the uploads management
  includes/admin.inc.php
Labels: bug

#372 Check update function
  includes/functions.inc.php
Labels: bug
