Repository My-Little-Forum/mylittleforum, pull requests merged in 2019-02, with the labels that each got.

#455 Fix: wrong syntax for UPDATE, used AND instead the correct comma
  includes/posting.inc.php
Labels: bug

#460 Clean update, rework of the update scripts for master branch
  config/VERSION
  config/db_settings.php
  install/index.php
  install/install.sql
  update/update.sql
  update/update_2.3.5-2.4.php
  update/update_2.4.19.1-2.5.php
Labels: work in progress

#461 Fix: CSS-changes for PR #364 wasn't taken over to the file style.min.css
  themes/default/style.min.css
Labels: bug

#462 Fix: remove one superfluous parenthese, caused a PHP-error
  includes/upload_image.inc.php
Labels: bug

#463 B8
  modules/b8/b8.php
  modules/b8/degenerator/degenerator_default.php
  modules/b8/lexer/lexer_default.php
  modules/b8/storage/storage_base.php
  modules/b8/storage/storage_mysqli.php
Labels: cleanup, next major version

#466 missing function call
  js/admin.js
  js/admin.min.js
Labels: bug
