Repository My-Little-Forum/mylittleforum, pull requests merged in 2019-05, with the labels that each got.

#470 Make it possible to restrict the access to the users list to admins and mods
  includes/user.inc.php
  install/install.sql
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/main.tpl
  themes/default/subtemplates/admin.inc.tpl
  themes/default/subtemplates/entry.inc.tpl
  themes/default/subtemplates/thread.inc.tpl
  themes/default/subtemplates/thread_linear.inc.tpl
  update/update_2.4.19.1-2.5.php
Labels: enhancement, feature

#471 Allow to pin a thread either to a category or to all categories (if at all)
  includes/posting.inc.php
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/subtemplates/index.inc.tpl
  themes/default/subtemplates/index_table.inc.tpl
  themes/default/subtemplates/posting.inc.tpl
Labels: enhancement, feature

#472 List sticky topics from other categories in category selection or a single, different category
  includes/index.inc.php
Labels: bug

#476 Fix: correct the path to images to an absolute URL in the RSS feed
  includes/rss.inc.php
Labels: bug

#475 Quote-Button
  js/posting.js
  js/posting.min.js
Labels: cleanup, work in progress
