Repository My-Little-Forum/mylittleforum, pull requests merged in 2019-01, with the labels that each got.

#439 Unicode character properties
  includes/register.inc.php
  includes/user.inc.php
Labels: enhancement

#441 Regexp
  includes/register.inc.php
  includes/user.inc.php
Labels: bug, cleanup

#442 Fix: thumbnails was elongated to the complete height of the entry
  themes/default/style.css
  themes/default/style.min.css
Labels: bug

#444 Fix: user_id must accept NULL values from unregistered users, …
  install/install.sql
Labels: bug

#445 Change: make the link text more descriptiv
  lang/english.lang
  lang/german.lang
Labels: cleanup

#446 Fix: deleting a posting could leave orphaned subscriptions
  includes/functions.inc.php
Labels: bug

#450 Introduction Elements
  js/posting.js
  js/posting.min.js
Labels: cleanup

#451 Store information about uploads in a database table
  config/db_settings.php
  includes/upload_image.inc.php
  install/index.php
  install/install.sql
Labels: enhancement, feature, work in progress

#454 Fix: no hardcoded table names, dammit!
  includes/upload_image.inc.php
Labels: bug
