Repository My-Little-Forum/mylittleforum, pull requests merged in 2019-06, with the labels that each got.

#479 Update functions.inc.php
  includes/functions.inc.php
Labels: cleanup

#478 Use the full width of 4 byte for UTF-8 to store text data in the database
  config/VERSION
  includes/admin.inc.php
  includes/functions.inc.php
  includes/user.inc.php
  install/install.sql
  update/update_2.4.19.1-2.5.php
Labels: discussion, enhancement, feature

#484 Notification mails
  includes/posting.inc.php
Labels: bug

#485 fix collation of wordlist table
  install/install.sql
Labels: bug

#487 remove checkbox for flash
  themes/default/subtemplates/admin.inc.tpl
Labels: cleanup

#489 B8 contact
  includes/admin.inc.php
  includes/contact.inc.php
  install/install.sql
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/subtemplates/admin.inc.tpl
  themes/default/subtemplates/contact.inc.tpl
  update/update_2.4.19.1-2.5.php
Labels: bug, feature

#490 Remove smarty code
  themes/default/subtemplates/contact.inc.tpl
Labels: bug

#488 UI-elements to handle spam/ham postings
  includes/main.inc.php
  includes/search.inc.php
  themes/default/subtemplates/index.inc.tpl
  themes/default/subtemplates/index_table.inc.tpl
Labels: cleanup, feature

#491 SPAM warning message
  includes/posting.inc.php
  update/update_2.4.19.1-2.5.php
Labels: bug

#493 B8 config file
  config/b8_config.php
  includes/contact.inc.php
  includes/posting.inc.php
  index.php
Labels: cleanup
