Repository My-Little-Forum/mylittleforum, pull requests merged in 2020-10, with the labels that each got.

#534 CSS for RSS of the Thread (Thread View)
  themes/default/style.css
  themes/default/style.min.css
Labels: bug, cleanup

#536 Add field user_type to the thread tree below a single entry
  includes/entry.inc.php
  themes/default/subtemplates/entry.inc.tpl
Labels: bug

#538 Fix: delete hyperfluous comma
  themes/default/style.css
Labels: bug

#543 Clean script files
  js/admin.js
  js/main.js
  js/posting.js
Labels: cleanup

#542 Same structure as in the threaded views for the single-entry-view
  themes/default/subtemplates/entry.inc.tpl
Labels: enhancement

#544 main.js
  js/main.js
Labels: bug

#545 DOMContentLoaded
  js/admin.js
  js/main.js
  js/posting.js
Labels: cleanup

#547 Change: alter the doctype, change from XHTML 1.0 strict to transitional
  themes/default/main.tpl
Labels: enhancement
