Repository My-Little-Forum/mylittleforum, pull requests merged in 2020-09, with the labels that each got.

#530 Change: add link to top of the page to every entry and the page footer
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/main.tpl
  themes/default/style.css
  themes/default/style.min.css
  themes/default/subtemplates/entry.inc.tpl
  themes/default/subtemplates/thread.inc.tpl
  themes/default/subtemplates/thread_linear.inc.tpl
Labels: enhancement

#531 Fix for invalid HTML structure introduced in #530
  themes/default/main.tpl
  themes/default/style.css
  themes/default/style.min.css
Labels: bug

#532 Corrected comment
  lang/chinese.lang
  lang/croatian.lang
  lang/danish.lang
  lang/french.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
Labels: bug, cleanup

#533 CSS for RSS of the Thread
  themes/default/style.css
  themes/default/style.min.css
Labels: bug, cleanup
