Repository My-Little-Forum/mylittleforum, pull requests merged in 2021-09, with the labels that each got.

#569 Chinese lang
  lang/chinese.lang
  lang/chinese_traditional.lang
Labels: enhancement

#570 CSRF
  includes/posting.inc.php
Labels: enhancement

#571 user lock state
  includes/functions.inc.php
Labels: enhancement

#572 Forgotten strings in traditional chinese for browser-window-target
  lang/chinese_traditional.lang
Labels: bug

#546 Link target
  js/main.js
Labels: feature

#573 Array name
  js/main.js
Labels: cleanup
