Repository My-Little-Forum/mylittleforum, pull requests merged in 2022-04, with the labels that each got.

#577 Typo
  lang/german.lang
Labels: cleanup

#578 Default target
  includes/js_defaults.inc.php
  js/main.js
  js/main.min.js
Labels: enhancement, dependency

#579 Type Error
  js/admin.min.js
Labels: bug

#580 Type Error
  js/posting.min.js
Labels: bug

#581 create_function (PHP 8)
  modules/geshi/geshi.php
Labels: bug, cleanup, next major version

#584 Passing null
  modules/smarty/plugins/shared.mb_str_replace.php
Labels: bug

#585 Automatic conversion
  includes/entry.inc.php
Labels: cleanup, next major version

#586 isset
  modules/smarty/plugins/shared.mb_str_replace.php
Labels: bug, cleanup, next major version

#587 strftime (PHP 8)
  includes/functions.inc.php
  lang/chinese.lang
  lang/chinese_traditional.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
Labels: cleanup, next major version

#588 Use modern HTML doctype
  themes/default/main.tpl
Labels: enhancement, cleanup

#593 Check database
  includes/functions.inc.php
Labels: bug
