Repository My-Little-Forum/mylittleforum, pull requests merged in 2024-11, with the labels that each got.

#761 ISO-timestamps
  includes/entry.inc.php
  lang/arabic.lang
  lang/chinese.lang
  lang/chinese_traditional.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/subtemplates/entry.inc.tpl
Labels: cleanup, frontend

#762 Date
  update/update_2.4.19-2.5.php
Labels: bug

#764 Scope of statement
  includes/index.inc.php
Labels: bug

#765 Code cleaning
  includes/index.inc.php
Labels: cleanup

#768 File filter
  includes/upload_image.inc.php
Labels: cleanup, frontend, fix

#769 Make WebP images appear in the uploaded-images browsing view
  includes/admin.inc.php
  includes/upload_image.inc.php
Labels: fix
