Repository My-Little-Forum/mylittleforum, pull requests merged in 2024-10, with the labels that each got.

#748 el.getAttribute("id") vs. el.id
  js/posting.js
  js/posting.min.js
Labels: bug

#749 Replace the element <strong> for the user or author name
  lang/arabic.lang
  lang/chinese.lang
  lang/chinese_traditional.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/style.min.css
  themes/default/subtemplates/admin.inc.tpl
  themes/default/subtemplates/bookmark.inc.tpl
  themes/default/subtemplates/entry.inc.tpl
  themes/default/subtemplates/index.inc.tpl
  themes/default/subtemplates/index_table.inc.tpl
  themes/default/subtemplates/search.inc.tpl
  themes/default/subtemplates/thread.inc.tpl
  themes/default/subtemplates/thread_linear.inc.tpl
  themes/default/subtemplates/user.inc.tpl
  themes/default/subtemplates/user_postings.inc.tpl
Labels: frontend

#752 user name
  themes/default/style.css
Labels: cleanup, frontend

#753 Unify the common CSS rules for the subject link under the class `.subject`
  themes/default/style.css
  themes/default/style.min.css
Labels: cleanup, frontend
