Repository My-Little-Forum/mylittleforum, pull requests merged in 2024-08, with the labels that each got.

#734 Fix the timeformat in the German language file
  lang/german.lang
Labels: bug, fix

#732 Put forgotten column for ORDER BY clause into the SELECT-section of the query
  includes/index.inc.php
Labels: fix, database

#736 SQL stm
  update/update_2.4.19-2.5.php
Labels: bug

#735 Collect the table names from the existing entries in $db_settings
  update/update_2.4.19-2.5.php
Labels: bug, fix

#737 Translate "sidebar" to "Barra laterale"
  lang/italian.lang
Labels: translation

#738 Format date and time in arabic language
  lang/arabic.lang
Labels: translation
