Repository My-Little-Forum/mylittleforum, pull requests merged in 2024-12, with the labels that each got.

#771 User id
  includes/functions.inc.php
Labels: bug, security

#772 Complete rework of the template of the upload popup
  themes/default/upload_image.tpl
Labels: bug, enhancement, frontend, fix

#775 Small fixes for forgotten changes in the avatar template
  themes/default/avatar.tpl
Labels: fix

#779 Missing information about MySQLi-errors in the upgrade script
  update/update_2.4.19-2.5.php
Labels: fix

#783 Access
  includes/user.inc.php
Labels: bug, cleanup

#785 Access v2.0
  includes/user.inc.php
Labels: bug
