Repository My-Little-Forum/mylittleforum, pull requests merged in 2025-07, with the labels that each got.

#842 Caution icon
  themes/default/subtemplates/entry.inc.tpl
  themes/default/subtemplates/thread.inc.tpl
  themes/default/subtemplates/thread_linear.inc.tpl
Labels: cleanup

#844 Replace the arrow below the user data table in the admin area
  themes/default/images/arrow_selected.png
  themes/default/style.css
  themes/default/style.min.css
Labels: frontend

#845 Add a button to select all displayed datasets in a table with the checkboxes of the data rows
  js/main.js
  lang/arabic.lang
  lang/chinese.lang
  lang/chinese_traditional.lang
  lang/croatian.lang
  lang/danish.lang
  lang/english.lang
  lang/french.lang
  lang/german.lang
  lang/italian.lang
  lang/norwegian.lang
  lang/russian.lang
  lang/spanish.lang
  lang/swedish.lang
  lang/tamil.lang
  lang/turkish.lang
  themes/default/style.css
  themes/default/style.min.css
  themes/default/subtemplates/admin.inc.tpl
Labels: feature, frontend

#846 No null value for array $last_posting
  includes/user.inc.php
Labels: bug, fix

#847 Initialise array $last_posting as array
  includes/user.inc.php
Labels: fix
