Repository My-Little-Forum/mylittleforum, pull requests merged in 2025-03, with the labels that each got.

#795 Permission
  includes/index.inc.php
Labels: bug

#798 Fixes for the upload management enhancements
  includes/admin.inc.php
Labels: bug, fix

#800 Fix #790: apply the changes to the template for sending an e-mail in case of a forgotten password
  themes/default/subtemplates/login_pw_forgotten.inc.tpl
Labels: frontend, fix

#802 Blank
  themes/default/subtemplates/posting.inc.tpl
Labels: frontend
